// Credit system — tracks usage per client, deducts per action type.
// client_id is a UUID generated by the frontend and stored in localStorage.
// No auth required — soft enforcement until proper login is built.

const PLAN_CREDITS = {
  free:           50,
  starter:        300,
  creator_pro:    500,
  pro:            1000,
  agency_starter: 3000,
  agency_pro:     10000,
};

const CREDIT_COSTS = {
  research:          0,   // DB-only queries — always free
  followup:          2,   // Conversational refinement in OUTPUT thread
  generation:        10,  // Script outline / body / ending, no web search
  generation_tavily: 15,  // Generation + Tavily web search
  generation_sonar:  25,  // Generation + Sonar Pro web search
  thumbnail:         40,  // Single thumbnail generation
  thumbnail_3x:      100, // 3 thumbnail generations (save 20 vs buying separately)
  voice:             5,   // Voice profile analysis
};

// Returns or creates the credit account for this client
function getOrCreate(db, clientId) {
  let acct = db.get('SELECT * FROM user_credits WHERE client_id = ?', [clientId]);
  if (!acct) {
    db.run(
      `INSERT INTO user_credits (client_id, plan, credits) VALUES (?, 'free', 50)`,
      [clientId],
    );
    acct = db.get('SELECT * FROM user_credits WHERE client_id = ?', [clientId]);
  }
  return acct;
}

// Total spendable credits (main + rollover + topup)
function totalBalance(acct) {
  return (acct.credits || 0) + (acct.rollover || 0) + (acct.topup || 0);
}

// Returns { ok, balance, plan } — check before any paid action
function canAfford(db, clientId, cost) {
  if (cost === 0) return { ok: true };
  const acct = getOrCreate(db, clientId);
  const bal  = totalBalance(acct);
  return { ok: bal >= cost, balance: bal, plan: acct.plan };
}

// Deduct credits. Order: topup → rollover → main credits
// Returns { deducted, balance }
function deduct(db, clientId, cost, action, threadId, channelId, meta) {
  if (cost === 0) {
    const acct = getOrCreate(db, clientId);
    return { deducted: 0, balance: totalBalance(acct) };
  }

  const acct = getOrCreate(db, clientId);
  let remaining = cost;
  let credits   = acct.credits  || 0;
  let rollover  = acct.rollover || 0;
  let topup     = acct.topup    || 0;

  if (topup >= remaining)    { topup    -= remaining; remaining = 0; }
  else                       { remaining -= topup; topup = 0; }

  if (remaining > 0) {
    if (rollover >= remaining) { rollover -= remaining; remaining = 0; }
    else                       { remaining -= rollover; rollover = 0; }
  }

  if (remaining > 0) { credits = Math.max(0, credits - remaining); }

  const newBalance = credits + rollover + topup;

  db.run(
    `UPDATE user_credits SET credits=?, rollover=?, topup=?, updated_at=datetime('now') WHERE client_id=?`,
    [credits, rollover, topup, clientId],
  );
  db.run(
    `INSERT INTO credit_transactions (client_id, action, amount, balance, thread_id, channel_id, meta)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [clientId, action, -cost, newBalance, threadId || null, channelId || null, JSON.stringify(meta || {})],
  );

  console.log(`[credits] deducted=${cost} action=${action} balance=${newBalance} client=${clientId.slice(0, 8)}`);
  return { deducted: cost, balance: newBalance };
}

// Classify what type of action just happened, based on the generated response.
// Called AFTER Claude responds — deduct based on what actually happened.
function classifyAction(parsedResponse, prevThreadState, webContext) {
  const cards        = parsedResponse?.cards || [];
  const hasGeneration = cards.some(c => c.type === 'outline' || c.type === 'script');

  if (!hasGeneration) {
    // Thread was at OUTPUT → this is a follow-up refinement (not a new generation)
    if (prevThreadState?.state === 'OUTPUT') {
      return { action: 'followup', cost: CREDIT_COSTS.followup };
    }
    // Pure research — peer/topic/opportunity/comparison queries
    return { action: 'research', cost: CREDIT_COSTS.research };
  }

  // Generation happened — determine if web search was used and which engine
  if (webContext) {
    const engine = webContext._engine || 'tavily';
    if (engine === 'sonar-pro') return { action: 'generation_sonar', cost: CREDIT_COSTS.generation_sonar };
    return { action: 'generation_tavily', cost: CREDIT_COSTS.generation_tavily };
  }

  return { action: 'generation', cost: CREDIT_COSTS.generation };
}

// Estimate max possible cost before the API call (for pre-flight credit check).
// We check for max so users with borderline credits aren't blocked on cheap actions.
function estimateMaxCost(compiledPolicy, prevThreadState) {
  if (prevThreadState?.state === 'OUTPUT') return CREDIT_COSTS.followup;
  if (compiledPolicy?.config?.needsWeb) return CREDIT_COSTS.generation_tavily; // worst case without Sonar Pro
  return CREDIT_COSTS.generation;
}

module.exports = { getOrCreate, totalBalance, canAfford, deduct, classifyAction, estimateMaxCost, PLAN_CREDITS, CREDIT_COSTS };
