'use strict';

/**
 * Hybrid Recommendation Audit — Phase 4
 *
 * Compares three recommendation generation strategies for the same set of creator channels:
 *   - DNA-only:   existing dna_original_bets traces
 *   - Peer-only:  existing peer_video_signal traces
 *   - Hybrid:     generated by hybridRecommendationGenerator.js
 *
 * Metrics:
 *   - Human quality labels (from gold set, where available)
 *   - Structure score (computed)
 *   - Creator relevance rate (concept_confidence >= 0.55)
 *   - Win rate (Good+Excellent labels / labeled count)
 *   - GENERIC share (template pattern detection)
 *   - Word count distribution
 *
 * Usage: node hybridRecommendationAudit.js [--verbose]
 *   Run hybridRecommendationGenerator.js first to generate hybrid_recommendations.json
 */

const path = require('path');
const fs   = require('fs');
const Database = require('../node_modules/better-sqlite3');
const { recommendationStructureScore } = require('./recommendationStructureScore');

const DB_PATH    = path.resolve(__dirname, '../data/scoring.db');
const HYBRID_IN  = path.resolve(__dirname, 'hybrid_recommendations.json');
const VERBOSE    = process.argv.includes('--verbose');

// ── Template classifier (for GENERIC share) ───────────────────────────────────
const IS_WINNER_TEMPLATE = t => {
  const s = String(t || '');
  if (/\b(biryani|vada pav|dosa|noodles|pasta|pizza|paneer|chicken|curry)\b/i.test(s)) return true;
  if (/^(how |what nobody|the best way)/i.test(s) || /\b(how to|way to)\b/i.test(s)) return true;
  if (/\b(checklist|guide|tips?|routine|plan)\s+(for|to)\b/i.test(s) || /\ba (practical|honest|quick|simple)\s+(checklist|guide)/i.test(s)) return true;
  if (/\b(mistake|trap|pitfall|wrong|hidden cost|beginner mistake|get wrong)\b/i.test(s)) return true;
  return false;
};

function wordCount(t) {
  return String(t || '').trim().split(/\s+/).filter(Boolean).length;
}
function pct(n, d) {
  if (!d) return '—';
  return (n / d * 100).toFixed(1) + '%';
}
function avg(arr) {
  if (!arr.length) return 0;
  return (arr.reduce((a, b) => a + b, 0) / arr.length).toFixed(1);
}

function computeMetrics(recs, goldByTitle) {
  if (!recs.length) return { n: 0 };
  const structScores   = [];
  const wcs            = [];
  let winner = 0, generic = 0, creatorRelevant = 0;
  let goldPos = 0, goldTotal = 0;

  for (const rec of recs) {
    const title = rec.hybrid_title || rec.generated_title || '';
    const { score } = recommendationStructureScore(title);
    structScores.push(score);
    wcs.push(wordCount(title));

    if (IS_WINNER_TEMPLATE(title)) winner++; else generic++;
    if ((rec.concept_confidence || 0) >= 0.55) creatorRelevant++;

    const gold = goldByTitle.get(title) || rec.gold_label;
    if (gold) {
      goldTotal++;
      if (gold === 'Excellent' || gold === 'Good') goldPos++;
    }
  }

  return {
    n: recs.length,
    struct_avg:      avg(structScores),
    wc_avg:          avg(wcs),
    winner_share:    pct(winner, recs.length),
    generic_share:   pct(generic, recs.length),
    creator_rel_rate:pct(creatorRelevant, recs.length),
    win_rate:        goldTotal ? pct(goldPos, goldTotal) : 'no gold labels',
    gold_labeled:    goldTotal,
  };
}

function main() {
  if (!fs.existsSync(HYBRID_IN)) {
    process.stderr.write('ERROR: hybrid_recommendations.json not found. Run hybridRecommendationGenerator.js first.\n');
    process.exit(1);
  }

  const hybridData = JSON.parse(fs.readFileSync(HYBRID_IN, 'utf8'));
  const hybridRecs = hybridData.hybrid_recommendations || [];

  const db = new Database(DB_PATH, { readonly: true, timeout: 60000 });

  // Load gold labels
  const goldByTitle = new Map();
  const goldRows = db.prepare("SELECT generated_title, human_label FROM wtp_human_quality_reviews WHERE human_label IS NOT NULL").all();
  for (const r of goldRows) goldByTitle.set(r.generated_title, r.human_label);

  // Get channels that appear in hybrid recs
  const hybridChannels = [...new Set(hybridRecs.map(r => r.channel_id))];

  // Load DNA-only traces for the same channels
  const dnaRecs = db.prepare(
    `SELECT generated_title, concept_confidence, rec_source
     FROM wtp_generation_traces
     WHERE channel_id IN (${hybridChannels.map(() => '?').join(',')})
       AND rec_source = 'dna_original_bets'
       AND generated_title IS NOT NULL`,
  ).all(...hybridChannels);

  // Load peer-only traces for the same channels
  const peerRecs = db.prepare(
    `SELECT generated_title, concept_confidence, rec_source
     FROM wtp_generation_traces
     WHERE channel_id IN (${hybridChannels.map(() => '?').join(',')})
       AND rec_source = 'peer_video_signal'
       AND generated_title IS NOT NULL`,
  ).all(...hybridChannels);

  db.close();

  // ── Compute metrics ───────────────────────────────────────────────────────
  const dnaMetrics    = computeMetrics(dnaRecs, goldByTitle);
  const peerMetrics   = computeMetrics(peerRecs, goldByTitle);
  const hybridMetrics = computeMetrics(hybridRecs, goldByTitle);

  // ── Console report ────────────────────────────────────────────────────────
  process.stdout.write('\n══════════════════════════════════════════════════════════════\n');
  process.stdout.write('  Hybrid Recommendation Audit\n');
  process.stdout.write(`  Channels analyzed: ${hybridChannels.length}\n`);
  process.stdout.write(`  DNA traces: ${dnaMetrics.n} | Peer traces: ${peerMetrics.n} | Hybrid: ${hybridMetrics.n}\n`);
  process.stdout.write('══════════════════════════════════════════════════════════════\n\n');

  const rows = [
    ['Recommendations', dnaMetrics.n, peerMetrics.n, hybridMetrics.n],
    ['Structure score avg', dnaMetrics.struct_avg, peerMetrics.struct_avg, hybridMetrics.struct_avg],
    ['Word count avg', dnaMetrics.wc_avg, peerMetrics.wc_avg, hybridMetrics.wc_avg],
    ['Winner template %', dnaMetrics.winner_share, peerMetrics.winner_share, hybridMetrics.winner_share],
    ['GENERIC %', dnaMetrics.generic_share, peerMetrics.generic_share, hybridMetrics.generic_share],
    ['Creator relevance %', dnaMetrics.creator_rel_rate, peerMetrics.creator_rel_rate, hybridMetrics.creator_rel_rate],
    ['Win rate (gold)', dnaMetrics.win_rate, peerMetrics.win_rate, hybridMetrics.win_rate],
    ['Gold labeled', dnaMetrics.gold_labeled, peerMetrics.gold_labeled, hybridMetrics.gold_labeled],
  ];

  process.stdout.write('  Metric                     DNA-only        Peer-only       Hybrid\n');
  process.stdout.write('  ' + '─'.repeat(70) + '\n');
  for (const [m, d, p, h] of rows) {
    process.stdout.write(`  ${m.padEnd(28)}${String(d).padEnd(16)}${String(p).padEnd(16)}${h}\n`);
  }

  process.stdout.write('\n── Hybrid by pattern type ────────────────────────────────────\n');
  const patterns = [...new Set(hybridRecs.map(r => r.peer_pattern))];
  for (const pattern of patterns) {
    const forPat = hybridRecs.filter(r => r.peer_pattern === pattern);
    const m = computeMetrics(forPat, goldByTitle);
    process.stdout.write(`  ${pattern.padEnd(20)} n=${forPat.length.toString().padEnd(5)} struct=${m.struct_avg}  winner%=${m.winner_share}  creator_rel%=${m.creator_rel_rate}\n`);
  }

  process.stdout.write('\n── Hybrid by creator family ──────────────────────────────────\n');
  const families = [...new Set(hybridRecs.map(r => r.creator_family))].sort();
  for (const fam of families) {
    const forFam = hybridRecs.filter(r => r.creator_family === fam);
    const m = computeMetrics(forFam, goldByTitle);
    const winLine = m.gold_labeled ? ` win=${m.win_rate}(${m.gold_labeled}labeled)` : '';
    process.stdout.write(`  ${fam.padEnd(28)} n=${forFam.length.toString().padEnd(5)} struct=${m.struct_avg}${winLine}\n`);
  }

  if (VERBOSE) {
    process.stdout.write('\n── Top hybrid titles (by structure score) ────────────────────\n');
    const top = [...hybridRecs].sort((a, b) => b.struct_score - a.struct_score).slice(0, 20);
    for (const r of top) {
      const gold = goldByTitle.get(r.hybrid_title) || '—';
      process.stdout.write(`  [${r.peer_pattern}][${r.creator_family}] "${r.hybrid_title}" struct=${r.struct_score} gold=${gold}\n`);
    }
  }

  // ── Verdict ───────────────────────────────────────────────────────────────
  process.stdout.write('\n── Verdict ───────────────────────────────────────────────────\n');
  const hybridStructNum = parseFloat(hybridMetrics.struct_avg);
  const dnaStructNum    = parseFloat(dnaMetrics.struct_avg);
  const peerStructNum   = parseFloat(peerMetrics.struct_avg);

  if (hybridMetrics.n < 10) {
    process.stdout.write('  INSUFFICIENT DATA: Not enough hybrid recs to draw conclusions.\n');
  } else if (hybridStructNum > dnaStructNum && hybridStructNum > peerStructNum) {
    process.stdout.write('  ✅ HYBRID OUTPERFORMS BOTH PARENTS on structure score.\n');
    process.stdout.write('     Recommendation: integrate hybrid generation into buildOriginalBetsFromDna().\n');
  } else if (hybridStructNum > dnaStructNum) {
    process.stdout.write('  ✅ HYBRID OUTPERFORMS DNA-ONLY on structure score.\n');
    process.stdout.write('     Peer-only still stronger (narrative signals). Hybrid improves DNA generation.\n');
  } else {
    process.stdout.write('  ⚠ HYBRID does not clearly outperform DNA-only on structure score.\n');
    process.stdout.write('     Check: are peer patterns thin? Are creator subjects low-quality?\n');
    process.stdout.write('     Consider: expand peer signal pool or improve subject filtering.\n');
  }

  process.stdout.write('\n  Next steps:\n');
  process.stdout.write('    1. Collect human labels on hybrid titles (add to wtp_human_quality_reviews)\n');
  process.stdout.write('    2. Compare win rate with more gold labels\n');
  process.stdout.write('    3. If hybrid wins: integrate into buildWinnerTemplateCandidates() as a source\n');
  process.stdout.write('    4. If hybrid ties DNA: use peer signal pool to drive WHICH winner templates to use\n');

  process.stdout.write('\n══════════════════════════════════════════════════════════════\n\n');
}

main();
