'use strict';

/**
 * Phase 6 helper — Title Comparison Export
 *
 * Exports a side-by-side comparison of template_title (engine-generated)
 * vs ai_title (AI-rewritten) for human reviewers to evaluate.
 *
 * Pulls from wtp_human_quality_reviews where the trace has both types,
 * and annotates each pair with its gold label (if already labelled).
 *
 * Output formats:
 *   console  — default, table view
 *   --export=FILE.json  — JSON for external review tool
 *
 * Usage:
 *   node wtpTitleComparisonExport.js [--export=FILE.json] [--source=dna_original_bets]
 *
 * Note:
 *   ai_title is generated by wtpRecommendationRefiner when ?refine=1 is called.
 *   The comparison data will populate over time as the refiner runs in production.
 *   This script can be re-run at any time to see the latest comparison data.
 */

const path = require('path');
const fs   = require('fs');
const BetterSqlite3 = require('../node_modules/better-sqlite3');

function openDb() {
  return new BetterSqlite3(path.resolve(__dirname, '../data/scoring.db'), {
    readonly: true,
    timeout:  60000,
  });
}

function main() {
  const args       = process.argv.slice(2);
  const exportFile = (args.find(a => a.startsWith('--export=')) || '').split('=')[1];
  const srcFilter  = (args.find(a => a.startsWith('--source=')) || '').split('=')[1];

  const db = openDb();

  // Check if wtp_refiner_cache has any ai_title data
  let cacheRows = [];
  try {
    cacheRows = db.prepare(`
      SELECT channel_id, payload_json, computed_at
      FROM wtp_refiner_cache
      WHERE expires_at > datetime('now')
      ORDER BY computed_at DESC
      LIMIT 50
    `).all();
  } catch (_) {}

  console.log('\n══════════════════════════════════════════════════════════════');
  console.log('  Phase 6 — Title Comparison Export');
  console.log('══════════════════════════════════════════════════════════════\n');

  if (cacheRows.length === 0) {
    console.log('  No refiner cache data found.');
    console.log('  The AI title comparison requires at least one call to:');
    console.log('    GET /api/intel/what-to-post?channel_id=CHANNEL_ID&refine=1');
    console.log('\n  Once production calls with ?refine=1 accumulate, re-run this script.');
    console.log('\n  What will be compared:');
    console.log('    template_title  — engine-generated title (current DNA/peer output)');
    console.log('    ai_title        — AI-rewritten title (from wtpRecommendationRefiner)');
    console.log('\n  Comparison dimensions for human reviewers:');
    console.log('    1. Specificity  — which title is more specific about the content?');
    console.log('    2. Filmability  — which title could a creator use as-is?');
    console.log('    3. Fit          — which title fits the creator\'s voice and niche?');
    console.log('    4. Clarity      — which title communicates value more clearly?');

    // Show what the gold set template titles look like as a baseline
    const goldRows = db.prepare(`
      SELECT batch_id, rec_source, generated_title, human_label, reviewer_notes
      FROM wtp_human_quality_reviews
      WHERE human_label IN ('Good', 'Excellent')
        AND rec_source = 'dna_original_bets'
      ORDER BY RANDOM()
      LIMIT 10
    `).all();

    if (goldRows.length > 0) {
      console.log('\n  Template title baseline (Good/Excellent DNA bets from gold set):');
      for (const r of goldRows) {
        console.log(`  [${r.human_label.padEnd(9)}] ${r.generated_title}`);
      }
    }

    console.log('\n══════════════════════════════════════════════════════════════\n');
    db.close();
    return;
  }

  // Parse refiner cache to extract template_title + ai_title pairs
  const pairs = [];
  for (const row of cacheRows) {
    let payload;
    try { payload = JSON.parse(row.payload_json); } catch { continue; }

    const ideas = Array.isArray(payload) ? payload : (payload.ideas || []);
    for (const idea of ideas) {
      if (!idea.template_title || !idea.ai_title) continue;
      if (srcFilter && idea.source !== srcFilter) continue;

      pairs.push({
        channel_id:     row.channel_id,
        computed_at:    row.computed_at,
        template_title: idea.template_title,
        ai_title:       idea.ai_title,
        topic:          idea.topic,
        score:          idea.score,
        rec_source:     idea.source || null,
        concept:        idea.concept?.id || null,
        refined_why:    idea.refinedWhy || null,
        best_angle:     idea.bestAngle  || null,
        // Reviewer fields (blank for human to fill)
        reviewer_preference: null,   // 'template' | 'ai' | 'tie'
        reviewer_reason:     null,
      });
    }
  }

  if (pairs.length === 0) {
    console.log('  Refiner cache has data but no template_title + ai_title pairs found.');
    console.log('  This means the refiner ran before the Phase 6 update.');
    console.log('  Clear the refiner cache or wait for TTL expiry (24h), then retry with ?refine=1.\n');
    db.close();
    return;
  }

  console.log(`  Found ${pairs.length} title pairs for comparison\n`);
  console.log('  Side-by-side comparison:\n');
  console.log('  ' + '─'.repeat(78));
  for (const p of pairs) {
    console.log(`  Channel: ${p.channel_id}`);
    console.log(`  Source:  ${p.rec_source || '-'}   Concept: ${p.concept || '-'}   Score: ${p.score || '-'}`);
    console.log(`  TEMPLATE: ${p.template_title}`);
    console.log(`  AI:       ${p.ai_title}`);
    if (p.best_angle) console.log(`  Angle:    ${p.best_angle}`);
    console.log('  ' + '─'.repeat(78));
  }

  if (exportFile) {
    fs.writeFileSync(exportFile, JSON.stringify(pairs, null, 2), 'utf8');
    console.log(`\n  Exported ${pairs.length} pairs to ${exportFile}`);
    console.log('  Fill in reviewer_preference ("template"|"ai"|"tie") and reviewer_reason for each.');
  }

  // Summary
  const withAi       = pairs.filter(p => p.ai_title).length;
  const withTemplate = pairs.filter(p => p.template_title).length;
  console.log(`\n  Pairs with template_title: ${withTemplate}   With ai_title: ${withAi}`);
  console.log('  Run again after human labelling to compare quality.\n');

  console.log('══════════════════════════════════════════════════════════════\n');
  db.close();
}

main();
